name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

env:
  # Keep for future abi3 usage (if you enable abi3 in Cargo.toml).
  PYO3_USE_ABI3_FORWARD_COMPATIBILITY: 1

jobs:
  build-linux:
    name: Build Linux (manylinux_2_17 x86_64; CPython only)
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      # Build only against CPython interpreters in the manylinux image.
      # This avoids PyPy 3.11 which pyo3 0.21.x doesn't support.
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          command: build
          manylinux: "2_17"  # PEP 600 tag (single platform tag)
          args: >-
            --release
            -i /opt/python/cp38-cp38/bin/python
            -i /opt/python/cp39-cp39/bin/python
            -i /opt/python/cp310-cp310/bin/python
            -i /opt/python/cp311-cp311/bin/python
            -i /opt/python/cp312-cp312/bin/python
            -i /opt/python/cp313-cp313/bin/python
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-linux
          path: target/wheels/*

  build-macos-arm64:
    name: Build macOS (arm64)
    runs-on: macos-14  # Use macos-14 for better reliability
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      
      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target/
          key: ${{ runner.os }}-arm64-cargo-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-arm64-cargo-
            ${{ runner.os }}-cargo-

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Build wheels (arm64)
        uses: PyO3/maturin-action@v1
        with:
          command: build
          args: >-
            --release
            --find-interpreter
        env:
          CARGO_INCREMENTAL: 0  # Disable incremental compilation for faster builds
          RUSTFLAGS: "-C target-cpu=native"  # Optimize for the build machine
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-macos-arm64
          path: target/wheels/*

  build-macos-x86_64:
    name: Build macOS (x86_64 via cross-compile)
    runs-on: macos-13  # Use Intel runner for x86_64 builds
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      
      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target/
          key: ${{ runner.os }}-x86_64-cargo-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-x86_64-cargo-
            ${{ runner.os }}-cargo-

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Build wheels (x86_64)
        uses: PyO3/maturin-action@v1
        with:
          command: build
          args: >-
            --release
            --find-interpreter
        env:
          CARGO_INCREMENTAL: 0  # Disable incremental compilation for faster builds
          MACOSX_DEPLOYMENT_TARGET: 11.0
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-macos-x86_64
          path: target/wheels/*

  build-windows:
    name: Build Windows (x86_64)
    runs-on: windows-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      
      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          command: build
          args: >-
            --release
            --find-interpreter
        env:
          CARGO_INCREMENTAL: 0  # Disable incremental compilation for faster builds
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-windows
          path: target/wheels/*

  build-sdist:
    name: Build sdist
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Build sdist
        uses: PyO3/maturin-action@v1
        with:
          command: sdist
      - name: Upload sdist
        uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: target/wheels/*.tar.gz

  release:
    name: Create GitHub Release & Publish to PyPI
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs:
      - build-linux
      - build-macos-arm64
      - build-macos-x86_64
      - build-windows
      - build-sdist
    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist-collect

      - name: Move artifacts to dist/
        run: |
          mkdir -p dist
          find dist-collect -name "*.whl" -exec mv {} dist/ \;
          find dist-collect -name "*.tar.gz" -exec mv {} dist/ \;
          ls -l dist

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to PyPI
        uses: PyO3/maturin-action@v1
        with:
          command: upload
          args: --skip-existing dist/*
        env:
          MATURIN_USERNAME: __token__
          MATURIN_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
          PYO3_USE_ABI3_FORWARD_COMPATIBILITY: 1
